mainConfig:
  type: esbuild
  path: esbuild.main.config.ts
  src: main.ts
  output:
    dir: dist/main
    filename: main.js

rendererConfig:
  type: vite
  path: vite.config.ts
  src: src/index.tsx
  output:
    dir: dist/renderer
