mainConfig:
  type: esbuild
  path: esbuild.main.config.ts
  src: src/electron/main.ts
  output:
    dir: dist/main
    filename: main.js

rendererConfig:
  type: vite
  path: vite.config.ts
  src: src/renderer/renderer.tsx
  output:
    dir: dist/renderer
